name: A workflow for my Hello World file
on: push

jobs:

  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'datalab'
      - name: Adding Known Hosts
        run: ssh-keyscan -H datalab.myconnectech.fr >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz . etienne@datalab.myconnectech.fr:~
      - uses: ./action-a
        with:
          MY_NAME: ${{ secrets.MY_NAME }}
